### ISSUE TITLE
Why dividing the depth_frame by 1000 while setting min_depth=0.7 

### ISSUE THREAD

**Issue by Ji4chenLi** [valtsblukis/hlsm#1]
Hi,

Thank you so much for releasing the wonderful implementations of HLSM!

I would like to ask why you divided the `depth_frame` from `event.depth_frame` while setting the `min_depth=0.7 `.
https://github.com/valtsblukis/hlsm/blob/c1aec8482e1e434c550db212efc0c01b87608b17/lgp/env/alfred/state_tracker.py#L281
https://github.com/valtsblukis/hlsm/blob/c1aec8482e1e434c550db212efc0c01b87608b17/lgp/models/alfred/projection/image_to_pointcloud.py#L26

From my experiment, it seems that such a `min_depth` will result in all `False` in the `has_depth` mask https://github.com/valtsblukis/hlsm/blob/c1aec8482e1e434c550db212efc0c01b87608b17/lgp/models/alfred/projection/image_to_pointcloud.py#L51

From the `ai2thor` documentation https://ai2thor.allenai.org/ithor/documentation/environment-state/#event-depth_frame , it seems that the `min_depth=0.7 ` is for the `event.depth_frame` without being divided by 1000.

Thanks,

Jiachen

**Comment by valtsblukis** [comment]
Hi Jiachen,

If I remember correctly, the dividing converts the values from millimeters to meters. The min-depth of 0.7 is in meters, and it's supposed to exclude objects that the agent is holding from the depth map. Otherwise in the map-building process, the held objects get added as obstacles and the agent would get stuck. There is definitely room for improvement in this mechanism.

**Comment by Ji4chenLi** [comment]
Hi Valts,

Thank you for your clarification! I just found that ALFRED uses AI2-THOR v2.1.0, in which the depth information is given in millimeters, but its unit changes to meters in v3.1.0. Below is a relevant issue from the ai2thor repo

https://github.com/allenai/ai2thor/issues/819
